language: nix
before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ https://datakurre.cachix.org/" | sudo tee -a /etc/nix/nix.conf
- echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= datakurre.cachix.org-1:ayZJTy5BDd8K4PW9uc9LHV+WCsdi/fu1ETIYZMooK78=" | sudo tee -a /etc/nix/nix.conf
script:
    - nix-shell setup.nix -A develop --argstr python $PYTHON --argstr requirements "$(pwd)/requirements-$REQUIREMENTS.nix" --run "flake8 src && robot -v BROWSER:headlessfirefox docs"
env:
- PYTHON=python2 REQUIREMENTS=python2
- PYTHON=python3 REQUIREMENTS=python3-travis
