# Generated by pip2nix 0.8.0.dev1
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Jinja2" = super.buildPythonPackage {
    name = "Jinja2-2.10";
    doCheck = false;
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/e6/332789f295cf22308386cf5bbd1f4e00ed11484299c5d7383378cf48ba47/Jinja2-2.10.tar.gz";
      sha256 = "190l36hfw3wb2n3n68yacjabxyb1pnxwn7vjx96cmjj002xy2jzq";
    };
  };
  "MarkupSafe" = super.buildPythonPackage {
    name = "MarkupSafe-1.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/7e/1b4c2e05809a4414ebce0892fe1e32c14ace86ca7d50c70f00979ca9b3a3/MarkupSafe-1.1.0.tar.gz";
      sha256 = "1lxirjypbdd3l9jl4vliilhfnhy7c7f2vlldqg1b0i74khn375sf";
    };
  };
  "Pygments" = super.buildPythonPackage {
    name = "Pygments-2.3.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/69/413708eaf3a64a6abb8972644e0f20891a55e621c6759e2c3f3891e05d63/Pygments-2.3.1.tar.gz";
      sha256 = "0ji87g09jph8jqcvclgb02qvxasdnr9pzvk90rl66d90yqcxmyjz";
    };
  };
  "alabaster" = super.buildPythonPackage {
    name = "alabaster-0.7.12";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/b4/ed8dcb0d67d5cfb7f83c4d5463a7614cb1d078ad7ae890c9143edebbf072/alabaster-0.7.12.tar.gz";
      sha256 = "00nwwjj2d2ym4s2kk217x7jkx1hnczc3fvm8yxbqmsp6b0nxfqd6";
    };
  };
  "atomicwrites" = super.buildPythonPackage {
    name = "atomicwrites-1.2.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/ed/a311712ef6b4355035489f665e63e1a73f9eb371929e3c98e5efd451069e/atomicwrites-1.2.1.tar.gz";
      sha256 = "1vmkbw9j0qammwxbxycrs39gvdg4lc2d4lk98kwf8ag2manyi6pc";
    };
  };
  "attrs" = super.buildPythonPackage {
    name = "attrs-18.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0f/9e/26b1d194aab960063b266170e53c39f73ea0d0d3f5ce23313e0ec8ee9bdf/attrs-18.2.0.tar.gz";
      sha256 = "0s9ydh058wmmf5v391pym877x4ahxg45dw6a0w4c7s5wgpigdjqh";
    };
  };
  "babel" = super.buildPythonPackage {
    name = "babel-2.6.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."pytz"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/cc/9c981b249a455fa0c76338966325fc70b7265521bad641bf2932f77712f4/Babel-2.6.0.tar.gz";
      sha256 = "08rxmbx2s4irp0w0gmn498vns5xy0fagm0fg33xa772jiks51flc";
    };
  };
  "certifi" = super.buildPythonPackage {
    name = "certifi-2018.11.29";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/55/54/3ce77783acba5979ce16674fc98b1920d00b01d337cfaaf5db22543505ed/certifi-2018.11.29.tar.gz";
      sha256 = "1dvccavd2fzq4j37w0sznylp92ps14zi6gvlxzm23in0yhzciya7";
    };
  };
  "chardet" = super.buildPythonPackage {
    name = "chardet-3.0.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz";
      sha256 = "1bpalpia6r5x1kknbk11p1fzph56fmmnp405ds8icksd3knr5aw4";
    };
  };
  "configparser" = super.buildPythonPackage {
    name = "configparser-3.5.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz";
      sha256 = "0fi7vf09vi1588jd8f16a021m5y6ih2hy7rpbjb408xw45qb822k";
    };
  };
  "docutils" = super.buildPythonPackage {
    name = "docutils-0.14";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/f4/5771e41fdf52aabebbadecc9381d11dea0fa34e4759b4071244fa094804c/docutils-0.14.tar.gz";
      sha256 = "0x22fs3pdmr42kvz6c654756wja305qv6cx1zbhwlagvxgr4xrji";
    };
  };
  "enum34" = super.buildPythonPackage {
    name = "enum34-1.1.6";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bf/3e/31d502c25302814a7c2f1d3959d2a3b3f78e509002ba91aea64993936876/enum34-1.1.6.tar.gz";
      sha256 = "1cgm5ng2gcfrkrm3hc22brl6chdmv67b9zvva9sfs7gn7dwc9n4a";
    };
  };
  "flake8" = super.buildPythonPackage {
    name = "flake8-3.6.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."configparser"
      self."enum34"
      self."mccabe"
      self."pycodestyle"
      self."pyflakes"
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d0/27/c0d1274b86a8f71ec1a6e4d4c1cfe3b20d6f95b090ec7545320150952c93/flake8-3.6.0.tar.gz";
      sha256 = "0w0nprx22rbvrrkbfx9v5jc5gskbm08g219l7r8wai8zfswgadba";
    };
  };
  "flake8-blind-except" = super.buildPythonPackage {
    name = "flake8-blind-except-0.1.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/f2/ab635e6e420e78c94eab50cd3f53abd3ec27e411793e50b14f29edbb9f0b/flake8-blind-except-0.1.1.tar.gz";
      sha256 = "16g58mkr3fcn2vlfhp3rlahj93qswc7jd5qrqp748mc26dk3b8xc";
    };
  };
  "flake8-coding" = super.buildPythonPackage {
    name = "flake8-coding-1.3.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/d7/889f7961ed549f15a280fa36edfc9b9016df38cd25cd0a8a7e4edc06efcf/flake8-coding-1.3.1.tar.gz";
      sha256 = "0i7qh5wmwh5bgf1lgi82nq2n6qks2jgv8pvr27dgw4c7q0i2p72l";
    };
  };
  "flake8-debugger" = super.buildPythonPackage {
    name = "flake8-debugger-3.1.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
      self."pycodestyle"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/4b/90548607282483dd15f9ce1f4434d735ae756e16e1faf60621b0f8877fcc/flake8-debugger-3.1.0.tar.gz";
      sha256 = "15qxrb2d7sr0pf024fkknsx58aqa5iz38b9s0panv3zfwf6vhkxy";
    };
  };
  "flake8-isort" = super.buildPythonPackage {
    name = "flake8-isort-2.6.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
      self."isort"
      self."testfixtures"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/85/fb/f2a33e47cf7520fd391e5f180cae5b8d2977ad7a5ddf897213137fe8a171/flake8-isort-2.6.0.tar.gz";
      sha256 = "0ajz616bif7sc02pm6fd41qs0n3dsx4lby5jrkfdpqynbm07q41w";
    };
  };
  "flake8-polyfill" = super.buildPythonPackage {
    name = "flake8-polyfill-1.0.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/67/1c26634a770db5c442e361311bee73cb3a177adb2eb3f7af8953cfd9f553/flake8-polyfill-1.0.2.tar.gz";
      sha256 = "1nlf1mkqw856vi6782qcglqhaacb23khk9wkcgn55npnjxshhjz4";
    };
  };
  "flake8-quotes" = super.buildPythonPackage {
    name = "flake8-quotes-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/83/ff/0461010959158bb7d197691c696f1a85b20f2d3eea7aa23f73a8d07f30f3/flake8-quotes-1.0.0.tar.gz";
      sha256 = "09ib440hrf5bbsmdbqzbcpkkqqnqdwkaawbqz93bbwxwifnjg4gx";
    };
  };
  "funcsigs" = super.buildPythonPackage {
    name = "funcsigs-1.0.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/94/4a/db842e7a0545de1cdb0439bb80e6e42dfe82aaeaadd4072f2263a4fbed23/funcsigs-1.0.2.tar.gz";
      sha256 = "0l4g5818ffyfmfs1a924811azhjj8ax9xd1cffr1mzd3ycn0zfx7";
    };
  };
  "futures" = super.buildPythonPackage {
    name = "futures-3.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1f/9e/7b2ff7e965fc654592269f2906ade1c7d705f1bf25b7d469fa153f7d19eb/futures-3.2.0.tar.gz";
      sha256 = "0rdjmmsab550kxsssdq49jcniz77zlkpw4pvi9hvib3lsskjmh4y";
    };
  };
  "idna" = super.buildPythonPackage {
    name = "idna-2.8";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/13/eb56951b6f7950cadb579ca166e448ba77f9d24efc03edd7e55fa57d04b7/idna-2.8.tar.gz";
      sha256 = "01rlkigdxg17sf9yar1jl8n18ls59367wqh59hnawlyg53vb6my3";
    };
  };
  "imagesize" = super.buildPythonPackage {
    name = "imagesize-1.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/41/f5/3cf63735d54aa9974e544aa25858d8f9670ac5b4da51020bbfc6aaade741/imagesize-1.1.0.tar.gz";
      sha256 = "1dg3wn7qpwmhgqc0r9na2ding1wif9q5spz3j9zn2riwphc2k0zk";
    };
  };
  "isort" = super.buildPythonPackage {
    name = "isort-4.3.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."futures"
      self."futures"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/de/a628d16fdba0d38cafb3d7e34d4830f2c9cb3881384ce5c08c44762e1846/isort-4.3.4.tar.gz";
      sha256 = "1y0yfv56cqyh9wyg7kxxv9y5wmfgcq18n7a49mp7xmzka2bhxi5r";
    };
  };
  "mccabe" = super.buildPythonPackage {
    name = "mccabe-0.6.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/18/fa675aa501e11d6d6ca0ae73a101b2f3571a565e0f7d38e062eec18a91ee/mccabe-0.6.1.tar.gz";
      sha256 = "07w3p1qm44hgxf3vvwz84kswpsx6s7kvaibzrsx5dzm0hli1i3fx";
    };
  };
  "more-itertools" = super.buildPythonPackage {
    name = "more-itertools-5.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/26/30fc0d541d9fdf55faf5ba4b0fd68f81d5bd2447579224820ad525934178/more-itertools-5.0.0.tar.gz";
      sha256 = "1r12cm6mcdwdzz7d47a6g4l437xsvapdlgyhqay3i2nrlv03da9q";
    };
  };
  "packaging" = super.buildPythonPackage {
    name = "packaging-18.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."pyparsing"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cf/50/1f10d2626df0aa97ce6b62cf6ebe14f605f4e101234f7748b8da4138a8ed/packaging-18.0.tar.gz";
      sha256 = "01wq9c53ix5rz6qg2c98gy8n4ff768rmanifm8m5jpjiaizj51h8";
    };
  };
  "pathlib2" = super.buildPythonPackage {
    name = "pathlib2-2.3.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."scandir"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bf/d7/a2568f4596b75d2c6e2b4094a7e64f620decc7887f69a1f2811931ea15b9/pathlib2-2.3.3.tar.gz";
      sha256 = "0hpp92vqqgcd8h92msm9slv161b1q160igjwnkf2ag6cx0c96695";
    };
  };
  "pep8-naming" = super.buildPythonPackage {
    name = "pep8-naming-0.7.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8-polyfill"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3e/4a/125425d6b1e017f48dfc9c961f4bb9510168db7a090618906c750184ed03/pep8-naming-0.7.0.tar.gz";
      sha256 = "09j8qg9wvrgp05drq81kfbd18wzz4p4nrhzkvalk5vq6vph5hhk2";
    };
  };
  "pillow" = super.buildPythonPackage {
    name = "pillow-5.3.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1b/e1/1118d60e9946e4e77872b69c58bc2f28448ec02c99a2ce456cd1a272c5fd/Pillow-5.3.0.tar.gz";
      sha256 = "14sgpkwccpkdnr9p1d1sw29ki3fdld4j773mibg4763psmy538rf";
    };
  };
  "pluggy" = super.buildPythonPackage {
    name = "pluggy-0.8.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/25/81d0de17cd00f8ca994a4e74e3c4baf7cd25072c0b831dad5c7d9d6138f8/pluggy-0.8.0.tar.gz";
      sha256 = "1580p47l2zqzsza8jcnw1h2wh3vvmygk6ly8bvi4w0g8j14sjys4";
    };
  };
  "py" = super.buildPythonPackage {
    name = "py-1.7.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c7/fa/eb6dd513d9eb13436e110aaeef9a1703437a8efa466ce6bb2ff1d9217ac7/py-1.7.0.tar.gz";
      sha256 = "152nyjvd8phqbm9pwlnfx0xi4c6343hakjzg42sp4qw3k1qn74mz";
    };
  };
  "pycodestyle" = super.buildPythonPackage {
    name = "pycodestyle-2.4.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/28/ad/cae9654d7fd64eb3d2ab2c44c9bf8dc5bd4fb759625beab99532239aa6e8/pycodestyle-2.4.0.tar.gz";
      sha256 = "0fhy4vnlgpjq4qd1wdnl6pvdw7rah0ypmn8c9mkhz8clsndskz6b";
    };
  };
  "pyflakes" = super.buildPythonPackage {
    name = "pyflakes-2.0.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/9e/386c0d9deef14996eb90d9deebbcb9d3ceb70296840b09615cb61b2ae231/pyflakes-2.0.0.tar.gz";
      sha256 = "0jba28czyvimdc72llms3f17swp3i8jdcabf5w0j00adfbn64xls";
    };
  };
  "pyparsing" = super.buildPythonPackage {
    name = "pyparsing-2.3.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d0/09/3e6a5eeb6e04467b737d55f8bba15247ac0876f98fae659e58cd744430c6/pyparsing-2.3.0.tar.gz";
      sha256 = "14k5v7n3xqw8kzf42x06bzp184spnlkya2dpjyflax6l3yrallzk";
    };
  };
  "pytest" = super.buildPythonPackage {
    name = "pytest-3.10.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."atomicwrites"
      self."attrs"
      self."funcsigs"
      self."more-itertools"
      self."pathlib2"
      self."pluggy"
      self."py"
      self."setuptools"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b5/96/37011e484665fab8b51add4f707d2aa28f1a06c68dd1c8a50e03551693b3/pytest-3.10.1.tar.gz";
      sha256 = "0q4n1p47p2bdblima035ga6yf5hkgd5jc1zw2yb9n5h17hbwyip2";
    };
  };
  "pytest-runner" = super.buildPythonPackage {
    name = "pytest-runner-4.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/b7/fe6e8f87f9a756fd06722216f1b6698ccba4d269eac6329d9f0c441d0f93/pytest-runner-4.2.tar.gz";
      sha256 = "1gkpyphawxz38ni1gdq1fmwyqcg02m7ypzqvv46z06crwdxi2gyj";
    };
  };
  "pytz" = super.buildPythonPackage {
    name = "pytz-2018.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cd/71/ae99fc3df1b1c5267d37ef2c51b7d79c44ba8a5e37b48e3ca93b4d74d98b/pytz-2018.7.tar.gz";
      sha256 = "1jin48jylhan9izpb7in6h43nlhvm7y7iwn56b6k7lypkg43bjri";
    };
  };
  "requests" = super.buildPythonPackage {
    name = "requests-2.21.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."certifi"
      self."chardet"
      self."idna"
      self."urllib3"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/2c/514e4ac25da2b08ca5a464c50463682126385c4272c18193876e91f4bc38/requests-2.21.0.tar.gz";
      sha256 = "13jr0wkj9c2j8c0c8iaal9iivi0bpxghnsdn6lxcpnmc657q4ajh";
    };
  };
  "robotframework" = super.buildPythonPackage {
    name = "robotframework-3.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dc/c9/34687fa751f6b3ad1a4b5b35f5ae1371b1c1b01e95007fbb03ac0732dc67/robotframework-3.1.zip";
      sha256 = "09r1rng8pngcfqmsnbl9d1dfvac2yx7zgjlym59zy0j4y70sb2xj";
    };
  };
  "robotframework-seleniumlibrary" = super.buildPythonPackage {
    name = "robotframework-seleniumlibrary-3.3.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."robotframework"
      self."selenium"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/44/d6efee0ea0bff85cf5618327184f8342659d338f98e8f71e0deb04542f95/robotframework-seleniumlibrary-3.3.0.tar.gz";
      sha256 = "1yrqm9sjkc9zcy2djvdx3aqslvpwv3p15q5fizyljig0qif9inda";
    };
  };
  "scandir" = super.buildPythonPackage {
    name = "scandir-1.9.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/2a/557af1181e6b4e30254d5a6163b18f5053791ca66e251e77ab08887e8fe3/scandir-1.9.0.tar.gz";
      sha256 = "0r3hvf1a9jm1rkqgx40gxkmccknkaiqjavs8lccgq9s8khh5x5s4";
    };
  };
  "selenium" = super.buildPythonPackage {
    name = "selenium-3.141.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."urllib3"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/9c/9030520bf6ff0b4c98988448a93c04fcbd5b13cd9520074d8ed53569ccfe/selenium-3.141.0.tar.gz";
      sha256 = "039hf9knvl4s3hp21bzwsp1g5ri9gxsh504dp48lc6nr1av35byy";
    };
  };
  "setuptools" = super.buildPythonPackage {
    name = "setuptools-40.6.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/37/1b/b25507861991beeade31473868463dad0e58b1978c209de27384ae541b0b/setuptools-40.6.3.zip";
      sha256 = "1y085dnk574sxw9aymdng9gijvrsbw86hsv9hqnhv7y4d6nlsirv";
    };
  };
  "setuptools-scm" = super.buildPythonPackage {
    name = "setuptools-scm-3.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/09/b4/d148a70543b42ff3d81d57381f33104f32b91f970ad7873f463e75bf7453/setuptools_scm-3.1.0.tar.gz";
      sha256 = "0h4bglwfz8b9prqljv8z3w9rgydfyxzaj05bm1y6zs5m6shz548i";
    };
  };
  "six" = super.buildPythonPackage {
    name = "six-1.12.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/bf/4138e7bfb757de47d1f4b6994648ec67a51efe58fa907c1e11e350cddfca/six-1.12.0.tar.gz";
      sha256 = "0wxs1q74v07ssjywbbm7x6h5v9qx209ld2yfsif4060sxi0h2sni";
    };
  };
  "snowballstemmer" = super.buildPythonPackage {
    name = "snowballstemmer-1.2.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/6b/d2a7cb176d4d664d94a6debf52cd8dbae1f7203c8e42426daa077051d59c/snowballstemmer-1.2.1.tar.gz";
      sha256 = "0a0idq4y5frv7qsg2x62jd7rd272749xk4x99misf5rcifk2d7wi";
    };
  };
  "sphinx" = super.buildPythonPackage {
    name = "sphinx-1.8.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."Jinja2"
      self."Pygments"
      self."alabaster"
      self."babel"
      self."docutils"
      self."imagesize"
      self."packaging"
      self."requests"
      self."setuptools"
      self."six"
      self."snowballstemmer"
      self."sphinxcontrib-websupport"
      self."typing"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4d/ed/4595274b5c9ce53a768cc0804ef65fd6282c956b93919a969e98d53894e4/Sphinx-1.8.3.tar.gz";
      sha256 = "1y5ry56rsmncd0n8aph6sg51bqn1mrmnnr0968ysxzxc8jx1gjy4";
    };
  };
  "sphinxcontrib-robotframework" = super.buildPythonPackage {
    name = "sphinxcontrib-robotframework-0.8.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."Pygments"
      self."robotframework"
      self."setuptools"
      self."sphinx"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c3/b1/4bf78bc6fbc0c34f4ddec87488b7c033452324deb11463a4970e5db69f10/sphinxcontrib-robotframework-0.8.0.tar.gz";
      sha256 = "00n70h565v3rdqzcc46vbr85a5rjrx356pph5fnb24f1araj5ikh";
    };
  };
  "sphinxcontrib-websupport" = super.buildPythonPackage {
    name = "sphinxcontrib-websupport-1.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/7a/e74b06dce85555ffee33e1d6b7381314169ebf7e31b62c18fcb2815626b7/sphinxcontrib-websupport-1.1.0.tar.gz";
      sha256 = "1ff3ix76xi1y6m99qxhaq5161ix9swwzydilvdya07mgbcvpzr4x";
    };
  };
  "testfixtures" = super.buildPythonPackage {
    name = "testfixtures-6.4.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/1c/0b694fbfd318e325888c3ac16776e9d1df452a90693d1d3734a5256fc793/testfixtures-6.4.1.tar.gz";
      sha256 = "0aa8jikyj2pl94b5i58ncs8dh44a53m66d3x2lprr04902gbah5h";
    };
  };
  "typing" = super.buildPythonPackage {
    name = "typing-3.6.6";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bf/9b/2bf84e841575b633d8d91ad923e198a415e3901f228715524689495b4317/typing-3.6.6.tar.gz";
      sha256 = "0ba9acs4awx15bf9v3nrs781msbd2nx826906nj6fqks2bvca9s0";
    };
  };
  "urllib3" = super.buildPythonPackage {
    name = "urllib3-1.24.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/53/37d82ab391393565f2f831b8eedbffd57db5a718216f82f1a8b4d381a1c1/urllib3-1.24.1.tar.gz";
      sha256 = "08lwd9f3hqznyf32vnzwvp87pchx062nkbgyrf67rwlkgj0jk5fy";
    };
  };
}
