# Generated by pip2nix 0.8.0.dev1
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "MarkupSafe" = super.buildPythonPackage {
    name = "MarkupSafe-1.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/7e/1b4c2e05809a4414ebce0892fe1e32c14ace86ca7d50c70f00979ca9b3a3/MarkupSafe-1.1.0.tar.gz";
      sha256 = "1lxirjypbdd3l9jl4vliilhfnhy7c7f2vlldqg1b0i74khn375sf";
    };
  };
  "Send2Trash" = super.buildPythonPackage {
    name = "Send2Trash-1.5.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/13/2e/ea40de0304bb1dc4eb309de90aeec39871b9b7c4bd30f1a3cdcb3496f5c0/Send2Trash-1.5.0.tar.gz";
      sha256 = "1ci8vcwjmjlp11ljj1ckrfmml9fkq1mclx2gr53y4zvhgp01q030";
    };
  };
  "atomicwrites" = super.buildPythonPackage {
    name = "atomicwrites-1.2.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/ed/a311712ef6b4355035489f665e63e1a73f9eb371929e3c98e5efd451069e/atomicwrites-1.2.1.tar.gz";
      sha256 = "1vmkbw9j0qammwxbxycrs39gvdg4lc2d4lk98kwf8ag2manyi6pc";
    };
  };
  "attrs" = super.buildPythonPackage {
    name = "attrs-18.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0f/9e/26b1d194aab960063b266170e53c39f73ea0d0d3f5ce23313e0ec8ee9bdf/attrs-18.2.0.tar.gz";
      sha256 = "0s9ydh058wmmf5v391pym877x4ahxg45dw6a0w4c7s5wgpigdjqh";
    };
  };
  "backcall" = super.buildPythonPackage {
    name = "backcall-0.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz";
      sha256 = "1r01dqch3f8fdj3n6fviw8hxqrs6w5v0qw4izmvqzry1w9dxiv1q";
    };
  };
  "bleach" = super.buildPythonPackage {
    name = "bleach-3.0.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."webencodings"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ae/31/680afc7d44040004296a2d8f0584983c2f2386448cd9d0964197e6c1160e/bleach-3.0.2.tar.gz";
      sha256 = "06474zg7f73hv8h1xw2wcsmvn2ygj73zxgxxqg8zcx8ap1srdls8";
    };
  };
  "decorator" = super.buildPythonPackage {
    name = "decorator-4.3.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6f/24/15a229626c775aae5806312f6bf1e2a73785be3402c0acdec5dbddd8c11e/decorator-4.3.0.tar.gz";
      sha256 = "0308djallnh00v112y5b7nadl657ysmkp6vc8xn51d6yzc9zm7n3";
    };
  };
  "defusedxml" = super.buildPythonPackage {
    name = "defusedxml-0.5.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/74/ba/4ba4e89e21b5a2e267d80736ea674609a0a33cc4435a6d748ef04f1f9374/defusedxml-0.5.0.tar.gz";
      sha256 = "1x54n0h8hl92vvwyymx883fbqpqjwn2mc8fb383bcg3z9zwz5mr4";
    };
  };
  "docutils" = super.buildPythonPackage {
    name = "docutils-0.14";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/f4/5771e41fdf52aabebbadecc9381d11dea0fa34e4759b4071244fa094804c/docutils-0.14.tar.gz";
      sha256 = "0x22fs3pdmr42kvz6c654756wja305qv6cx1zbhwlagvxgr4xrji";
    };
  };
  "entrypoints" = super.buildPythonPackage {
    name = "entrypoints-0.2.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/e8/607697e6ab8a961fc0b141a97ea4ce72cd9c9e264adeb0669f6d194aa626/entrypoints-0.2.3.tar.gz";
      sha256 = "17q21k8igjb47b73jn4w6lgzza1nscn3sf1sn5gm96bgw3fqgmfj";
    };
  };
  "flake8" = super.buildPythonPackage {
    name = "flake8-3.6.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."mccabe"
      self."pycodestyle"
      self."pyflakes"
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d0/27/c0d1274b86a8f71ec1a6e4d4c1cfe3b20d6f95b090ec7545320150952c93/flake8-3.6.0.tar.gz";
      sha256 = "0w0nprx22rbvrrkbfx9v5jc5gskbm08g219l7r8wai8zfswgadba";
    };
  };
  "flake8-blind-except" = super.buildPythonPackage {
    name = "flake8-blind-except-0.1.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/f2/ab635e6e420e78c94eab50cd3f53abd3ec27e411793e50b14f29edbb9f0b/flake8-blind-except-0.1.1.tar.gz";
      sha256 = "16g58mkr3fcn2vlfhp3rlahj93qswc7jd5qrqp748mc26dk3b8xc";
    };
  };
  "flake8-coding" = super.buildPythonPackage {
    name = "flake8-coding-1.3.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/d7/889f7961ed549f15a280fa36edfc9b9016df38cd25cd0a8a7e4edc06efcf/flake8-coding-1.3.1.tar.gz";
      sha256 = "0i7qh5wmwh5bgf1lgi82nq2n6qks2jgv8pvr27dgw4c7q0i2p72l";
    };
  };
  "flake8-debugger" = super.buildPythonPackage {
    name = "flake8-debugger-3.1.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
      self."pycodestyle"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/4b/90548607282483dd15f9ce1f4434d735ae756e16e1faf60621b0f8877fcc/flake8-debugger-3.1.0.tar.gz";
      sha256 = "15qxrb2d7sr0pf024fkknsx58aqa5iz38b9s0panv3zfwf6vhkxy";
    };
  };
  "flake8-isort" = super.buildPythonPackage {
    name = "flake8-isort-2.6.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
      self."isort"
      self."testfixtures"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/85/fb/f2a33e47cf7520fd391e5f180cae5b8d2977ad7a5ddf897213137fe8a171/flake8-isort-2.6.0.tar.gz";
      sha256 = "0ajz616bif7sc02pm6fd41qs0n3dsx4lby5jrkfdpqynbm07q41w";
    };
  };
  "flake8-polyfill" = super.buildPythonPackage {
    name = "flake8-polyfill-1.0.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/67/1c26634a770db5c442e361311bee73cb3a177adb2eb3f7af8953cfd9f553/flake8-polyfill-1.0.2.tar.gz";
      sha256 = "1nlf1mkqw856vi6782qcglqhaacb23khk9wkcgn55npnjxshhjz4";
    };
  };
  "flake8-quotes" = super.buildPythonPackage {
    name = "flake8-quotes-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/83/ff/0461010959158bb7d197691c696f1a85b20f2d3eea7aa23f73a8d07f30f3/flake8-quotes-1.0.0.tar.gz";
      sha256 = "09ib440hrf5bbsmdbqzbcpkkqqnqdwkaawbqz93bbwxwifnjg4gx";
    };
  };
  "future" = super.buildPythonPackage {
    name = "future-0.17.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz";
      sha256 = "1f2rlqn9rh7adgir52dlbqz69gsab44x0mlm8gf1cs7xvhv54137";
    };
  };
  "ipykernel" = super.buildPythonPackage {
    name = "ipykernel-5.1.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipython"
      self."jupyter-client"
      self."tornado"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/11/0b/95330660f8cc5d63428b9886c800ea8d68842fd866389cf579acca4915be/ipykernel-5.1.0.tar.gz";
      sha256 = "0br95qhrd5k65g10djngiy27hs0642301hlf2q142i8djabvzh0g";
    };
  };
  "ipython" = super.buildPythonPackage {
    name = "ipython-7.2.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."backcall"
      self."decorator"
      self."jedi"
      self."pexpect"
      self."pickleshare"
      self."prompt-toolkit"
      self."pygments"
      self."setuptools"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/bb/0ed1fb1d57d697326f9e9b827d9a74b81dee56031ed7c252bc716195ad7a/ipython-7.2.0.tar.gz";
      sha256 = "04nxpgv05qizmwcr5swbndaizbwsj4lbjshjxhfkyiknkch9d53a";
    };
  };
  "ipython-genutils" = super.buildPythonPackage {
    name = "ipython-genutils-0.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/69/fbeffffc05236398ebfcfb512b6d2511c622871dca1746361006da310399/ipython_genutils-0.2.0.tar.gz";
      sha256 = "1a4bc9y8hnvq6cp08qs4mckgm6i6ajpndp4g496rvvzcfmp12bpb";
    };
  };
  "ipywidgets" = super.buildPythonPackage {
    name = "ipywidgets-7.4.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."nbformat"
      self."traitlets"
      self."widgetsnbextension"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/88/8d/c5d3ac1bdcd74c7327c733c9d02354ff12d7d72744f262ed1e26560962b2/ipywidgets-7.4.2.tar.gz";
      sha256 = "18qbvygzii06ygwnrgjbqaqcmnssqlph96mb8xq7cgqn63s29qm3";
    };
  };
  "isort" = super.buildPythonPackage {
    name = "isort-4.3.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/de/a628d16fdba0d38cafb3d7e34d4830f2c9cb3881384ce5c08c44762e1846/isort-4.3.4.tar.gz";
      sha256 = "1y0yfv56cqyh9wyg7kxxv9y5wmfgcq18n7a49mp7xmzka2bhxi5r";
    };
  };
  "jedi" = super.buildPythonPackage {
    name = "jedi-0.13.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."parso"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e4/83/4c05db437252694660c972b5374b35a68a8a0a8cd012dc95e5fd4d7e71b0/jedi-0.13.2.tar.gz";
      sha256 = "1za944msp0f8x36qa8l309jhv0kzlsdh7r9nj3z12y8npnsh45sp";
    };
  };
  "jinja2" = super.buildPythonPackage {
    name = "jinja2-2.10";
    doCheck = false;
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/e6/332789f295cf22308386cf5bbd1f4e00ed11484299c5d7383378cf48ba47/Jinja2-2.10.tar.gz";
      sha256 = "190l36hfw3wb2n3n68yacjabxyb1pnxwn7vjx96cmjj002xy2jzq";
    };
  };
  "jsonschema" = super.buildPythonPackage {
    name = "jsonschema-3.0.0a3";
    doCheck = false;
    propagatedBuildInputs = [
      self."attrs"
      self."pyrsistent"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/47/e1/afd760aa29665e61142811ef6ea8b8f79e43574ac8427473a11f6e918a10/jsonschema-3.0.0a3.tar.gz";
      sha256 = "0pkhsq91rhk6384p0jxjkhc9yml2ya2l0mysyq78sb4981h45n6z";
    };
  };
  "jupyter" = super.buildPythonPackage {
    name = "jupyter-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipywidgets"
      self."jupyter-console"
      self."nbconvert"
      self."notebook"
      self."qtconsole"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/a9/371d0b8fe37dd231cf4b2cff0a9f0f25e98f3a73c3771742444be27f2944/jupyter-1.0.0.tar.gz";
      sha256 = "0pwf3pminkzyzgx5kcplvvbvwrrzd3baa7lmh96f647k30rlpp6r";
    };
  };
  "jupyter-client" = super.buildPythonPackage {
    name = "jupyter-client-5.2.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."jupyter-core"
      self."python-dateutil"
      self."pyzmq"
      self."tornado"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e5/5c/f9b2182a445e3a6a8204daf04193154c474220f836dbcedc7d139276600e/jupyter_client-5.2.4.tar.gz";
      sha256 = "0l9mh7ccrpl3lppym3dnky8n1nk7xarzzdcxf4q2s7aw203cpydm";
    };
  };
  "jupyter-console" = super.buildPythonPackage {
    name = "jupyter-console-6.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."jupyter-client"
      self."prompt-toolkit"
      self."pygments"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/c8/b7e768a3dec19b09d8ad5296a479e03c19a741a1bb4abab27c09236b8562/jupyter_console-6.0.0.tar.gz";
      sha256 = "1xdjw11cppf1fxvwkw2bk13ckkwas3bdah8baingn9296mvfi31h";
    };
  };
  "jupyter-core" = super.buildPythonPackage {
    name = "jupyter-core-4.4.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b6/2d/2804f4de3a95583f65e5dcb4d7c8c7183124882323758996e867f47e72af/jupyter_core-4.4.0.tar.gz";
      sha256 = "1dy083rarba8prn9f9srxq3c7n7vyql02ycrqq306c40lr57aw5s";
    };
  };
  "jupyterlab" = super.buildPythonPackage {
    name = "jupyterlab-0.35.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."jupyterlab-server"
      self."notebook"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/4f/e8f51e797e6c4a580551141a9cc9ef38235d0cc3b1920d8bb3bacb58c927/jupyterlab-0.35.4.tar.gz";
      sha256 = "0mdlzsgn4brvbrnmhqar05rm356m27znndk15kbwl3v40cl0pfny";
    };
  };
  "jupyterlab-server" = super.buildPythonPackage {
    name = "jupyterlab-server-0.2.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."jsonschema"
      self."notebook"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b6/8c/5013d8e1e1c9cac3754344cc1d8693de6021cb717569bf18c455555558f4/jupyterlab_server-0.2.0.tar.gz";
      sha256 = "10xp3f6ixak5srdclpggc0kinvaacvcgdpl5p36q1a2p76kidnbj";
    };
  };
  "lunr" = super.buildPythonPackage {
    name = "lunr-0.5.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."future"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a9/a2/d73f932f990e37410a333e8d6de17064cfc07aac90fad15399a368c00b39/lunr-0.5.4.tar.gz";
      sha256 = "11r30vr46savspdk31qmw1xk5f6v7j135aqxadc1f3bdfyk58lhq";
    };
  };
  "mccabe" = super.buildPythonPackage {
    name = "mccabe-0.6.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/18/fa675aa501e11d6d6ca0ae73a101b2f3571a565e0f7d38e062eec18a91ee/mccabe-0.6.1.tar.gz";
      sha256 = "07w3p1qm44hgxf3vvwz84kswpsx6s7kvaibzrsx5dzm0hli1i3fx";
    };
  };
  "mistune" = super.buildPythonPackage {
    name = "mistune-0.8.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2d/a4/509f6e7783ddd35482feda27bc7f72e65b5e7dc910eca4ab2164daf9c577/mistune-0.8.4.tar.gz";
      sha256 = "0vkmsh0x480rni51lhyvigfdf06b9247z868pk3bal1wnnfl58sr";
    };
  };
  "more-itertools" = super.buildPythonPackage {
    name = "more-itertools-5.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/26/30fc0d541d9fdf55faf5ba4b0fd68f81d5bd2447579224820ad525934178/more-itertools-5.0.0.tar.gz";
      sha256 = "1r12cm6mcdwdzz7d47a6g4l437xsvapdlgyhqay3i2nrlv03da9q";
    };
  };
  "nbconvert" = super.buildPythonPackage {
    name = "nbconvert-5.4.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."bleach"
      self."defusedxml"
      self."entrypoints"
      self."jinja2"
      self."jupyter-core"
      self."mistune"
      self."nbformat"
      self."pandocfilters"
      self."pygments"
      self."testpath"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/88/68/0417164f344ad702245424d8f998b5c99f1c6147ad1ad645a465ae932134/nbconvert-5.4.0.tar.gz";
      sha256 = "01vqq099xk4mr6i27r9p4grkfwvbmw2575yva29am4i5jygp98m8";
    };
  };
  "nbformat" = super.buildPythonPackage {
    name = "nbformat-4.4.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipython-genutils"
      self."jsonschema"
      self."jupyter-core"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/0e/160754f7ae3e984863f585a3743b0ed1702043a81245907c8fae2d537155/nbformat-4.4.0.tar.gz";
      sha256 = "00nlf08h8yc4q73nphfvfhxrcnilaqanb8z0mdy6nxk0vzq4wjgp";
    };
  };
  "notebook" = super.buildPythonPackage {
    name = "notebook-5.7.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."Send2Trash"
      self."ipykernel"
      self."ipython-genutils"
      self."jinja2"
      self."jupyter-client"
      self."jupyter-core"
      self."nbconvert"
      self."nbformat"
      self."prometheus-client"
      self."pyzmq"
      self."terminado"
      self."tornado"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/22/b5dcce67559d63d0f22e46d806305710808c698a1b91c07eb09e389785e0/notebook-5.7.4.tar.gz";
      sha256 = "0jm7324mbxljmn9hgapj66q7swyz5ai92blmr0jpcy0h80x6f26r";
    };
  };
  "pandocfilters" = super.buildPythonPackage {
    name = "pandocfilters-1.4.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4c/ea/236e2584af67bb6df960832731a6e5325fd4441de001767da328c33368ce/pandocfilters-1.4.2.tar.gz";
      sha256 = "1a8d9b7s48gmq9zj0pmbyv2sivn5i7m6mybgpkk4jm5vd7hp1pdk";
    };
  };
  "parso" = super.buildPythonPackage {
    name = "parso-0.3.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/46/31/60de7c9cbb97cac56b193a5b61a1fd4d21df84843a570b370ec34781316b/parso-0.3.1.tar.gz";
      sha256 = "18p89iwcm8mnf380f92g9w0bhx5km8wxp392vvjcq4y1ld1llw1m";
    };
  };
  "pexpect" = super.buildPythonPackage {
    name = "pexpect-4.6.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ptyprocess"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/89/43/07d07654ee3e25235d8cea4164cdee0ec39d1fda8e9203156ebe403ffda4/pexpect-4.6.0.tar.gz";
      sha256 = "1fla85g47iaxxpjhp9vkxdnv4pgc7rplfy6ja491smrrk0jqi3ia";
    };
  };
  "pickleshare" = super.buildPythonPackage {
    name = "pickleshare-0.7.5";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d8/b6/df3c1c9b616e9c0edbc4fbab6ddd09df9535849c64ba51fcb6531c32d4d8/pickleshare-0.7.5.tar.gz";
      sha256 = "1jmghg3c53yp1i8cm6pcrm280ayi8621rwyav9fac7awjr3kss47";
    };
  };
  "pillow" = super.buildPythonPackage {
    name = "pillow-5.3.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1b/e1/1118d60e9946e4e77872b69c58bc2f28448ec02c99a2ce456cd1a272c5fd/Pillow-5.3.0.tar.gz";
      sha256 = "14sgpkwccpkdnr9p1d1sw29ki3fdld4j773mibg4763psmy538rf";
    };
  };
  "pluggy" = super.buildPythonPackage {
    name = "pluggy-0.8.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/25/81d0de17cd00f8ca994a4e74e3c4baf7cd25072c0b831dad5c7d9d6138f8/pluggy-0.8.0.tar.gz";
      sha256 = "1580p47l2zqzsza8jcnw1h2wh3vvmygk6ly8bvi4w0g8j14sjys4";
    };
  };
  "prometheus-client" = super.buildPythonPackage {
    name = "prometheus-client-0.5.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/e1/3cddac03c8992815519c5f50493097f6508fa153d067b494db8ab5e9c4ce/prometheus_client-0.5.0.tar.gz";
      sha256 = "0g7rpv1pq2lab1nfqdx98z9d3bqwc400alg1j4ynrpjkrbsizhg8";
    };
  };
  "prompt-toolkit" = super.buildPythonPackage {
    name = "prompt-toolkit-2.0.7";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."wcwidth"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/a5/4b2dd1a05403e34c3ba0d9c00f237c01967c0a4f59a427c9b241129cdfe4/prompt_toolkit-2.0.7.tar.gz";
      sha256 = "0fgacqk73w7s932vy46pan2yp8rvjmlkag20xvaydh9mhf6h85zx";
    };
  };
  "ptyprocess" = super.buildPythonPackage {
    name = "ptyprocess-0.6.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7d/2d/e4b8733cf79b7309d84c9081a4ab558c89d8c89da5961bf4ddb050ca1ce0/ptyprocess-0.6.0.tar.gz";
      sha256 = "1h4lcd3w5nrxnsk436ar7fwkiy5rfn5wj2xwy9l0r4mdqnf2jgwj";
    };
  };
  "py" = super.buildPythonPackage {
    name = "py-1.7.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c7/fa/eb6dd513d9eb13436e110aaeef9a1703437a8efa466ce6bb2ff1d9217ac7/py-1.7.0.tar.gz";
      sha256 = "152nyjvd8phqbm9pwlnfx0xi4c6343hakjzg42sp4qw3k1qn74mz";
    };
  };
  "pycodestyle" = super.buildPythonPackage {
    name = "pycodestyle-2.4.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/28/ad/cae9654d7fd64eb3d2ab2c44c9bf8dc5bd4fb759625beab99532239aa6e8/pycodestyle-2.4.0.tar.gz";
      sha256 = "0fhy4vnlgpjq4qd1wdnl6pvdw7rah0ypmn8c9mkhz8clsndskz6b";
    };
  };
  "pyflakes" = super.buildPythonPackage {
    name = "pyflakes-2.0.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/9e/386c0d9deef14996eb90d9deebbcb9d3ceb70296840b09615cb61b2ae231/pyflakes-2.0.0.tar.gz";
      sha256 = "0jba28czyvimdc72llms3f17swp3i8jdcabf5w0j00adfbn64xls";
    };
  };
  "pygments" = super.buildPythonPackage {
    name = "pygments-2.3.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/69/413708eaf3a64a6abb8972644e0f20891a55e621c6759e2c3f3891e05d63/Pygments-2.3.1.tar.gz";
      sha256 = "0ji87g09jph8jqcvclgb02qvxasdnr9pzvk90rl66d90yqcxmyjz";
    };
  };
  "pyrsistent" = super.buildPythonPackage {
    name = "pyrsistent-0.14.8";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b8/63/7c1cb7359d3c4170bc5415d9d204b2f37b7f09bea8982f125d905833192b/pyrsistent-0.14.8.tar.gz";
      sha256 = "0qmwid31090gwb2f82xx5icyqb7dyjl9m5mjj9c534y27b1hr22r";
    };
  };
  "pytest" = super.buildPythonPackage {
    name = "pytest-4.0.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."atomicwrites"
      self."attrs"
      self."more-itertools"
      self."pluggy"
      self."py"
      self."setuptools"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9d/a9/3688b67467527c25e7a4d02c3b22565f15158a0a5d681870bfda8af210c6/pytest-4.0.2.tar.gz";
      sha256 = "1sgq8nm7yb9ygapdjgn52zr0ny47gps5dpa86d08aiccq4pvz2gn";
    };
  };
  "pytest-runner" = super.buildPythonPackage {
    name = "pytest-runner-4.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/b7/fe6e8f87f9a756fd06722216f1b6698ccba4d269eac6329d9f0c441d0f93/pytest-runner-4.2.tar.gz";
      sha256 = "1gkpyphawxz38ni1gdq1fmwyqcg02m7ypzqvv46z06crwdxi2gyj";
    };
  };
  "python-dateutil" = super.buildPythonPackage {
    name = "python-dateutil-2.7.5";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0e/01/68747933e8d12263d41ce08119620d9a7e5eb72c876a3442257f74490da0/python-dateutil-2.7.5.tar.gz";
      sha256 = "00ngwcdw36w5b37b51mdwn3qxid9zdf3kpffv2q6n9kl05y2iyc8";
    };
  };
  "pyzmq" = super.buildPythonPackage {
    name = "pyzmq-17.1.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/6a/bc9277b78f5c3236e36b8c16f4d2701a7fd4fa2eb697159d3e0a3a991573/pyzmq-17.1.2.tar.gz";
      sha256 = "1pyxxrz60f88ffm0y6vpbx3q8jcr9ybz8fcilihwzwhh36n84ax7";
    };
  };
  "qtconsole" = super.buildPythonPackage {
    name = "qtconsole-4.4.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython-genutils"
      self."jupyter-client"
      self."jupyter-core"
      self."pygments"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/77/ab/43b1f5e27d712d9b7bb599afff32686465c32765e14f05a5c92b991b706d/qtconsole-4.4.3.tar.gz";
      sha256 = "1b03n1ixzscm0jw97l4dq5iy4fslnqxq5bb8287xb7n2a1gs26xw";
    };
  };
  "robotframework" = super.buildPythonPackage {
    name = "robotframework-3.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dc/c9/34687fa751f6b3ad1a4b5b35f5ae1371b1c1b01e95007fbb03ac0732dc67/robotframework-3.1.zip";
      sha256 = "09r1rng8pngcfqmsnbl9d1dfvac2yx7zgjlym59zy0j4y70sb2xj";
    };
  };
  "robotframework-seleniumlibrary" = super.buildPythonPackage {
    name = "robotframework-seleniumlibrary-3.3.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."robotframework"
      self."selenium"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/44/d6efee0ea0bff85cf5618327184f8342659d338f98e8f71e0deb04542f95/robotframework-seleniumlibrary-3.3.0.tar.gz";
      sha256 = "1yrqm9sjkc9zcy2djvdx3aqslvpwv3p15q5fizyljig0qif9inda";
    };
  };
  "robotkernel" = super.buildPythonPackage {
    name = "robotkernel-0.9.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."docutils"
      self."ipykernel"
      self."lunr"
      self."nbformat"
      self."pillow"
      self."pygments"
      self."robotframework"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4d/14/4468f42869c575d23af4f2dec22c665e483e4c8047fca239213fe25b429b/robotkernel-0.9.0.tar.gz";
      sha256 = "1y7yc1xiyccwr25qk6i94zy4406hrib6l1wn6i9r3ij3fkn01yfi";
    };
  };
  "selenium" = super.buildPythonPackage {
    name = "selenium-3.141.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."urllib3"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/9c/9030520bf6ff0b4c98988448a93c04fcbd5b13cd9520074d8ed53569ccfe/selenium-3.141.0.tar.gz";
      sha256 = "039hf9knvl4s3hp21bzwsp1g5ri9gxsh504dp48lc6nr1av35byy";
    };
  };
  "setuptools" = super.buildPythonPackage {
    name = "setuptools-40.6.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/37/1b/b25507861991beeade31473868463dad0e58b1978c209de27384ae541b0b/setuptools-40.6.3.zip";
      sha256 = "1y085dnk574sxw9aymdng9gijvrsbw86hsv9hqnhv7y4d6nlsirv";
    };
  };
  "setuptools-scm" = super.buildPythonPackage {
    name = "setuptools-scm-3.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/09/b4/d148a70543b42ff3d81d57381f33104f32b91f970ad7873f463e75bf7453/setuptools_scm-3.1.0.tar.gz";
      sha256 = "0h4bglwfz8b9prqljv8z3w9rgydfyxzaj05bm1y6zs5m6shz548i";
    };
  };
  "six" = super.buildPythonPackage {
    name = "six-1.12.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/bf/4138e7bfb757de47d1f4b6994648ec67a51efe58fa907c1e11e350cddfca/six-1.12.0.tar.gz";
      sha256 = "0wxs1q74v07ssjywbbm7x6h5v9qx209ld2yfsif4060sxi0h2sni";
    };
  };
  "terminado" = super.buildPythonPackage {
    name = "terminado-0.8.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."ptyprocess"
      self."tornado"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/67/84/ce0ebd0f60e1cbe040f8e065eef7063855d59d9cf5e6438b3f8439fc7e15/terminado-0.8.1.tar.gz";
      sha256 = "0yh69k6579g848rmjyllb5h75pkvgcy27r1l3yzgkf33wnnzkasm";
    };
  };
  "testfixtures" = super.buildPythonPackage {
    name = "testfixtures-6.4.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/1c/0b694fbfd318e325888c3ac16776e9d1df452a90693d1d3734a5256fc793/testfixtures-6.4.1.tar.gz";
      sha256 = "0aa8jikyj2pl94b5i58ncs8dh44a53m66d3x2lprr04902gbah5h";
    };
  };
  "testpath" = super.buildPythonPackage {
    name = "testpath-0.4.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/30/9a7e917066d851d8b4117e85794b5f14516419ea714a8a2681ec6aa8a981/testpath-0.4.2.tar.gz";
      sha256 = "1y40hywscnnyb734pnzm55nd8r8kp1072bjxbil83gcd53cv755n";
    };
  };
  "tornado" = super.buildPythonPackage {
    name = "tornado-5.1.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/78/6e7b5af12c12bdf38ca9bfe863fcaf53dc10430a312d0324e76c1e5ca426/tornado-5.1.1.tar.gz";
      sha256 = "02clqk2116jbnq8lnaqmdw3p52nqrd9ib59r4xz2ll43fpcmhlaf";
    };
  };
  "traitlets" = super.buildPythonPackage {
    name = "traitlets-4.3.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."decorator"
      self."ipython-genutils"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a5/98/7f5ef2fe9e9e071813aaf9cb91d1a732e0a68b6c44a32b38cb8e14c3f069/traitlets-4.3.2.tar.gz";
      sha256 = "0dbq7sx26xqz5ixs711k5nc88p8a0nqyz6162pwks5dpcz9d4jww";
    };
  };
  "urllib3" = super.buildPythonPackage {
    name = "urllib3-1.24.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/53/37d82ab391393565f2f831b8eedbffd57db5a718216f82f1a8b4d381a1c1/urllib3-1.24.1.tar.gz";
      sha256 = "08lwd9f3hqznyf32vnzwvp87pchx062nkbgyrf67rwlkgj0jk5fy";
    };
  };
  "wcwidth" = super.buildPythonPackage {
    name = "wcwidth-0.1.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/55/11/e4a2bb08bb450fdbd42cc709dd40de4ed2c472cf0ccb9e64af22279c5495/wcwidth-0.1.7.tar.gz";
      sha256 = "0pn6dflzm609m4r3i8ik5ni9ijjbb5fa3vg1n7hn6vkd49r77wrx";
    };
  };
  "webencodings" = super.buildPythonPackage {
    name = "webencodings-0.5.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0b/02/ae6ceac1baeda530866a85075641cec12989bd8d31af6d5ab4a3e8c92f47/webencodings-0.5.1.tar.gz";
      sha256 = "08qrgrc4hrximb2gqnl69g01s93rhf2842jfxdjljc1dbwj1qsmk";
    };
  };
  "widgetsnbextension" = super.buildPythonPackage {
    name = "widgetsnbextension-3.4.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."notebook"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cb/37/ec01aac3e510645959795337bf652155cd7efb28aecc940b0773e8ba8e4d/widgetsnbextension-3.4.2.tar.gz";
      sha256 = "0rc2nivdy7k4m3vljx7wdh2jh11djapcgwhvzlbs0isl8gl8nqgs";
    };
  };
  "yapf" = super.buildPythonPackage {
    name = "yapf-0.25.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/78/066d92807c532b4bdbfece8fcb5a20130df0476dfa924d6108f72f4efabf/yapf-0.25.0.tar.gz";
      sha256 = "0mbdyhqwlm4pcd0wr5haxypxm0kr8y46nc17696xmd4pvfmzk9wa";
    };
  };
}
